name: Python CD

on:
  release:
    types: [created]

permissions: {}

jobs:
  deploy:
    name: Publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flask-paseto-extended
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Install uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
      with:
        python-version: "3.13"
        enable-cache: false
    - name: Build the project
      run: uv build
    - name: Show result
      run: ls -l dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
